package com.example.sensebox.ui.theme

import androidx.compose.ui.graphics.Color

val boxLightPrimary = Color(0xFF825500)
val boxLightOnPrimary = Color(0xFFFFFFFF)
val boxLightPrimaryContainer = Color(0xFFFFDDAE)
val boxLightOnPrimaryContainer = Color(0xFF2A1800)
val boxLightSecondary = Color(0xFF6F5B40)
val boxLightOnSecondary = Color(0xFFFFFFFF)
val boxLightSecondaryContainer = Color(0xFFFADEBC)
val boxLightOnSecondaryContainer = Color(0xFF271904)
val boxLightTertiary = Color(0xFF516440)
val boxLightOnTertiary = Color(0xFFFFFFFF)
val boxLightTertiaryContainer = Color(0xFFD3EABC)
val boxLightOnTertiaryContainer = Color(0xFF102004)
val boxLightError = Color(0xFFBA1B1B)
val boxLightErrorContainer = Color(0xFFFFDAD4)
val boxLightOnError = Color(0xFFFFFFFF)
val boxLightOnErrorContainer = Color(0xFF410001)
val boxLightBackground = Color(0xFFFCFCFC)
val boxLightOnBackground = Color(0xFF1F1B16)
val boxLightSurface = Color(0xFFFCFCFC)
val boxLightOnSurface = Color(0xFF1F1B16)
val boxLightSurfaceVariant = Color(0xFFF0E0CF)
val boxLightOnSurfaceVariant = Color(0xFF4F4539)
val boxLightOutline = Color(0xFF817567)
val boxLightInverseOnSurface = Color(0xFFF9EFE6)
val boxLightInverseSurface = Color(0xFF34302A)
val boxLightPrimaryInverse = Color(0xFFFFB945)


val boxDarkPrimary = Color(0xFFFFB945)
val boxDarkOnPrimary = Color(0xFF452B00)
val boxDarkPrimaryContainer = Color(0xFF624000)
val boxDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val boxDarkSecondary = Color(0xFFDDC3A2)
val boxDarkOnSecondary = Color(0xFF3E2E16)
val boxDarkSecondaryContainer = Color(0xFF56442B)
val boxDarkOnSecondaryContainer = Color(0xFFFADEBC)
val boxDarkTertiary = Color(0xFFB8CEA2)
val boxDarkOnTertiary = Color(0xFF243516)
val boxDarkTertiaryContainer = Color(0xFF3A4C2B)
val boxDarkOnTertiaryContainer = Color(0xFFD3EABC)
val boxDarkError = Color(0xFFFFB4A9)
val boxDarkErrorContainer = Color(0xFF930006)
val boxDarkOnError = Color(0xFF680003)
val boxDarkOnErrorContainer = Color(0xFFFFDAD4)
val boxDarkBackground = Color(0xFF1F1B16)
val boxDarkOnBackground = Color(0xFFEAE1D9)
val boxDarkSurface = Color(0xFF1F1B16)
val boxDarkOnSurface = Color(0xFFEAE1D9)
val boxDarkSurfaceVariant = Color(0xFF4F4539)
val boxDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val boxDarkOutline = Color(0xFF9C8F80)
val boxDarkInverseOnSurface = Color(0xFF1F1B16)
val boxDarkInverseSurface = Color(0xFFEAE1D9)
val boxDarkPrimaryInverse = Color(0xFF825500)